# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0002_auto_20180709_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team_score',
            field=models.IntegerField(null=True, verbose_name='Away Team Score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_score',
            field=models.IntegerField(null=True, verbose_name='Home Team Score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.CharField(choices=[('11:30', '11:30'), ('11:45', '11:45'), ('12:00', '12:00'), ('12:30', '12:30'), ('12:45', '12:45'), ('1:00', '1:00'), ('1:30', '1:30'), ('1:45', '1:45'), ('2:00', '2:00'), ('2:30', '2:30'), ('2:45', '2:45'), ('3:00', '3:00'), ('3:30', '3:30'), ('3:45', '3:45'), ('4:00', '4:00'), ('4:30', '4:30'), ('4:45', '4:45'), ('5:00', '5:00'), ('5:30', '5:30'), ('5:45', '5:45'), ('6:00', '6:00'), ('6:30', '6:30'), ('6:45', '6:45'), ('7:00', '7:00'), ('7:30', '7:30'), ('7:45', '7:45'), ('8:00', '8:00')], max_length=5, verbose_name='Game Time'),
        ),
    ]
