# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0004_auto_20180709_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, verbose_name='Team Name')),
                ('team_color', models.CharField(max_length=30, verbose_name='Team Color')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team',
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseball.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.CharField(choices=[('11:00', '11:00'), ('11:30', '11:30'), ('11:45', '11:45'), ('12:00', '12:00'), ('12:30', '12:30'), ('12:45', '12:45'), ('1:00', '1:00'), ('1:30', '1:30'), ('1:45', '1:45'), ('2:00', '2:00'), ('2:30', '2:30'), ('2:45', '2:45'), ('3:00', '3:00'), ('3:30', '3:30'), ('3:45', '3:45'), ('4:00', '4:00'), ('4:30', '4:30'), ('4:45', '4:45'), ('5:00', '5:00'), ('5:30', '5:30'), ('5:45', '5:45'), ('6:00', '6:00'), ('6:30', '6:30'), ('6:45', '6:45'), ('7:00', '7:00'), ('7:30', '7:30'), ('7:45', '7:45'), ('8:00', '8:00')], max_length=5, verbose_name='Game Time'),
        ),
    ]
