# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0005_auto_20180710_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='baseball.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='baseball.Team'),
        ),
    ]
