# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0006_auto_20180710_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='D2_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sept', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=4, verbose_name='Month')),
                ('day', models.IntegerField(verbose_name='Day')),
                ('time', models.CharField(choices=[('11:00', '11:00'), ('11:30', '11:30'), ('11:45', '11:45'), ('12:00', '12:00'), ('12:30', '12:30'), ('12:45', '12:45'), ('1:00', '1:00'), ('1:30', '1:30'), ('1:45', '1:45'), ('2:00', '2:00'), ('2:30', '2:30'), ('2:45', '2:45'), ('3:00', '3:00'), ('3:30', '3:30'), ('3:45', '3:45'), ('4:00', '4:00'), ('4:30', '4:30'), ('4:45', '4:45'), ('5:00', '5:00'), ('5:30', '5:30'), ('5:45', '5:45'), ('6:00', '6:00'), ('6:30', '6:30'), ('6:45', '6:45'), ('7:00', '7:00'), ('7:30', '7:30'), ('7:45', '7:45'), ('8:00', '8:00')], max_length=5, verbose_name='Game Time')),
                ('away_team_score', models.IntegerField(blank=True, null=True, verbose_name='Away Team Score')),
                ('home_team_score', models.IntegerField(blank=True, null=True, verbose_name='Home Team Score')),
            ],
        ),
        migrations.CreateModel(
            name='D2_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, verbose_name='Team Name')),
                ('team_color', models.CharField(max_length=30, verbose_name='Team Color')),
            ],
        ),
        migrations.CreateModel(
            name='D3_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sept', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], max_length=4, verbose_name='Month')),
                ('day', models.IntegerField(verbose_name='Day')),
                ('time', models.CharField(choices=[('11:00', '11:00'), ('11:30', '11:30'), ('11:45', '11:45'), ('12:00', '12:00'), ('12:30', '12:30'), ('12:45', '12:45'), ('1:00', '1:00'), ('1:30', '1:30'), ('1:45', '1:45'), ('2:00', '2:00'), ('2:30', '2:30'), ('2:45', '2:45'), ('3:00', '3:00'), ('3:30', '3:30'), ('3:45', '3:45'), ('4:00', '4:00'), ('4:30', '4:30'), ('4:45', '4:45'), ('5:00', '5:00'), ('5:30', '5:30'), ('5:45', '5:45'), ('6:00', '6:00'), ('6:30', '6:30'), ('6:45', '6:45'), ('7:00', '7:00'), ('7:30', '7:30'), ('7:45', '7:45'), ('8:00', '8:00')], max_length=5, verbose_name='Game Time')),
                ('away_team_score', models.IntegerField(blank=True, null=True, verbose_name='Away Team Score')),
                ('home_team_score', models.IntegerField(blank=True, null=True, verbose_name='Home Team Score')),
            ],
        ),
        migrations.CreateModel(
            name='D3_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, verbose_name='Team Name')),
                ('team_color', models.CharField(max_length=30, verbose_name='Team Color')),
            ],
        ),
        migrations.RenameModel(
            old_name='Game',
            new_name='D1_Game',
        ),
        migrations.RenameModel(
            old_name='Team',
            new_name='D1_Team',
        ),
        migrations.AddField(
            model_name='d3_game',
            name='away_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='baseball.D3_Team'),
        ),
        migrations.AddField(
            model_name='d3_game',
            name='home_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='baseball.D3_Team'),
        ),
        migrations.AddField(
            model_name='d2_game',
            name='away_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='baseball.D2_Team'),
        ),
        migrations.AddField(
            model_name='d2_game',
            name='home_team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='baseball.D2_Team'),
        ),
    ]
